default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: anthology_development

test:
  <<: *default
  database: anthology_test

production:
  <<: *default
  database: anthology_production
